// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: muxcore/notification/v1/notification.proto

package notificationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Channel int32

const (
	Channel_CHANNEL_UNSPECIFIED Channel = 0
	Channel_CHANNEL_DISCORD     Channel = 1
	Channel_CHANNEL_SLACK       Channel = 2
	Channel_CHANNEL_WEBHOOK     Channel = 3
	Channel_CHANNEL_EMAIL       Channel = 4
	Channel_CHANNEL_APPRISE     Channel = 5
)

// Enum value maps for Channel.
var (
	Channel_name = map[int32]string{
		0: "CHANNEL_UNSPECIFIED",
		1: "CHANNEL_DISCORD",
		2: "CHANNEL_SLACK",
		3: "CHANNEL_WEBHOOK",
		4: "CHANNEL_EMAIL",
		5: "CHANNEL_APPRISE",
	}
	Channel_value = map[string]int32{
		"CHANNEL_UNSPECIFIED": 0,
		"CHANNEL_DISCORD":     1,
		"CHANNEL_SLACK":       2,
		"CHANNEL_WEBHOOK":     3,
		"CHANNEL_EMAIL":       4,
		"CHANNEL_APPRISE":     5,
	}
)

func (x Channel) Enum() *Channel {
	p := new(Channel)
	*p = x
	return p
}

func (x Channel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Channel) Descriptor() protoreflect.EnumDescriptor {
	return file_muxcore_notification_v1_notification_proto_enumTypes[0].Descriptor()
}

func (Channel) Type() protoreflect.EnumType {
	return &file_muxcore_notification_v1_notification_proto_enumTypes[0]
}

func (x Channel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Channel.Descriptor instead.
func (Channel) EnumDescriptor() ([]byte, []int) {
	return file_muxcore_notification_v1_notification_proto_rawDescGZIP(), []int{0}
}

// Severity drives portable Discord/Slack color mapping across implementers.
type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_SEVERITY_INFO        Severity = 1
	Severity_SEVERITY_SUCCESS     Severity = 2
	Severity_SEVERITY_WARNING     Severity = 3
	Severity_SEVERITY_ERROR       Severity = 4
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "SEVERITY_INFO",
		2: "SEVERITY_SUCCESS",
		3: "SEVERITY_WARNING",
		4: "SEVERITY_ERROR",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"SEVERITY_INFO":        1,
		"SEVERITY_SUCCESS":     2,
		"SEVERITY_WARNING":     3,
		"SEVERITY_ERROR":       4,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_muxcore_notification_v1_notification_proto_enumTypes[1].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_muxcore_notification_v1_notification_proto_enumTypes[1]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_muxcore_notification_v1_notification_proto_rawDescGZIP(), []int{1}
}

type NotifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Severity      Severity               `protobuf:"varint,3,opt,name=severity,proto3,enum=muxcore.notification.v1.Severity" json:"severity,omitempty"`
	SourceModule  string                 `protobuf:"bytes,4,opt,name=source_module,json=sourceModule,proto3" json:"source_module,omitempty"`                                           // module that triggered the notification
	Channels      []Channel              `protobuf:"varint,5,rep,packed,name=channels,proto3,enum=muxcore.notification.v1.Channel" json:"channels,omitempty"`                          // empty = all configured channels
	Fields        map[string]string      `protobuf:"bytes,6,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // additional structured fields
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyRequest) Reset() {
	*x = NotifyRequest{}
	mi := &file_muxcore_notification_v1_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyRequest) ProtoMessage() {}

func (x *NotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_muxcore_notification_v1_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyRequest.ProtoReflect.Descriptor instead.
func (*NotifyRequest) Descriptor() ([]byte, []int) {
	return file_muxcore_notification_v1_notification_proto_rawDescGZIP(), []int{0}
}

func (x *NotifyRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NotifyRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NotifyRequest) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *NotifyRequest) GetSourceModule() string {
	if x != nil {
		return x.SourceModule
	}
	return ""
}

func (x *NotifyRequest) GetChannels() []Channel {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *NotifyRequest) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type NotifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ChannelResult       `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyResponse) Reset() {
	*x = NotifyResponse{}
	mi := &file_muxcore_notification_v1_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyResponse) ProtoMessage() {}

func (x *NotifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_muxcore_notification_v1_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyResponse.ProtoReflect.Descriptor instead.
func (*NotifyResponse) Descriptor() ([]byte, []int) {
	return file_muxcore_notification_v1_notification_proto_rawDescGZIP(), []int{1}
}

func (x *NotifyResponse) GetResults() []*ChannelResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type ChannelResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       Channel                `protobuf:"varint,1,opt,name=channel,proto3,enum=muxcore.notification.v1.Channel" json:"channel,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelResult) Reset() {
	*x = ChannelResult{}
	mi := &file_muxcore_notification_v1_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelResult) ProtoMessage() {}

func (x *ChannelResult) ProtoReflect() protoreflect.Message {
	mi := &file_muxcore_notification_v1_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelResult.ProtoReflect.Descriptor instead.
func (*ChannelResult) Descriptor() ([]byte, []int) {
	return file_muxcore_notification_v1_notification_proto_rawDescGZIP(), []int{2}
}

func (x *ChannelResult) GetChannel() Channel {
	if x != nil {
		return x.Channel
	}
	return Channel_CHANNEL_UNSPECIFIED
}

func (x *ChannelResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ChannelResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ConfigureRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Channel Channel                `protobuf:"varint,1,opt,name=channel,proto3,enum=muxcore.notification.v1.Channel" json:"channel,omitempty"`
	// Per-channel settings. Canonical keys (implementers MUST accept these names):
	//
	// Discord, Slack, Webhook:
	//
	//	webhook_url — HTTPS webhook endpoint
	//
	// Email:
	//
	//	smtp_host, smtp_port, smtp_user, smtp_pass, smtp_from, to
	//
	// Apprise:
	//
	//	urls — comma-separated Apprise URLs
	//	token — optional Apprise API token
	//
	// Aliases such as "host", "from", or "pass" are non-portable; callers should use the keys above.
	Settings map[string]string `protobuf:"bytes,2,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// When false, disable the channel (clear active configuration). When true or unset, upsert settings.
	Enabled       bool `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_muxcore_notification_v1_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_muxcore_notification_v1_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_muxcore_notification_v1_notification_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigureRequest) GetChannel() Channel {
	if x != nil {
		return x.Channel
	}
	return Channel_CHANNEL_UNSPECIFIED
}

func (x *ConfigureRequest) GetSettings() map[string]string {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *ConfigureRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type ConfigureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configured    bool                   `protobuf:"varint,1,opt,name=configured,proto3" json:"configured,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_muxcore_notification_v1_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_muxcore_notification_v1_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return file_muxcore_notification_v1_notification_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigureResponse) GetConfigured() bool {
	if x != nil {
		return x.Configured
	}
	return false
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_muxcore_notification_v1_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_muxcore_notification_v1_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_muxcore_notification_v1_notification_proto_rawDescGZIP(), []int{5}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channels      []*ChannelStatus       `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_muxcore_notification_v1_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_muxcore_notification_v1_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_muxcore_notification_v1_notification_proto_rawDescGZIP(), []int{6}
}

func (x *StatusResponse) GetChannels() []*ChannelStatus {
	if x != nil {
		return x.Channels
	}
	return nil
}

type ChannelStatus struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Channel Channel                `protobuf:"varint,1,opt,name=channel,proto3,enum=muxcore.notification.v1.Channel" json:"channel,omitempty"`
	Enabled bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Human-readable label (channel type, recipient hint). Must NOT include webhook URLs,
	// SMTP credentials, Apprise tokens, or other secrets.
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	LastError     string                 `protobuf:"bytes,4,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	LastSuccessAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_success_at,json=lastSuccessAt,proto3" json:"last_success_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelStatus) Reset() {
	*x = ChannelStatus{}
	mi := &file_muxcore_notification_v1_notification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelStatus) ProtoMessage() {}

func (x *ChannelStatus) ProtoReflect() protoreflect.Message {
	mi := &file_muxcore_notification_v1_notification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelStatus.ProtoReflect.Descriptor instead.
func (*ChannelStatus) Descriptor() ([]byte, []int) {
	return file_muxcore_notification_v1_notification_proto_rawDescGZIP(), []int{7}
}

func (x *ChannelStatus) GetChannel() Channel {
	if x != nil {
		return x.Channel
	}
	return Channel_CHANNEL_UNSPECIFIED
}

func (x *ChannelStatus) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ChannelStatus) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ChannelStatus) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *ChannelStatus) GetLastSuccessAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSuccessAt
	}
	return nil
}

type TestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       Channel                `protobuf:"varint,1,opt,name=channel,proto3,enum=muxcore.notification.v1.Channel" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestRequest) Reset() {
	*x = TestRequest{}
	mi := &file_muxcore_notification_v1_notification_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRequest) ProtoMessage() {}

func (x *TestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_muxcore_notification_v1_notification_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRequest.ProtoReflect.Descriptor instead.
func (*TestRequest) Descriptor() ([]byte, []int) {
	return file_muxcore_notification_v1_notification_proto_rawDescGZIP(), []int{8}
}

func (x *TestRequest) GetChannel() Channel {
	if x != nil {
		return x.Channel
	}
	return Channel_CHANNEL_UNSPECIFIED
}

type TestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *ChannelResult         `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestResponse) Reset() {
	*x = TestResponse{}
	mi := &file_muxcore_notification_v1_notification_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResponse) ProtoMessage() {}

func (x *TestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_muxcore_notification_v1_notification_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResponse.ProtoReflect.Descriptor instead.
func (*TestResponse) Descriptor() ([]byte, []int) {
	return file_muxcore_notification_v1_notification_proto_rawDescGZIP(), []int{9}
}

func (x *TestResponse) GetResult() *ChannelResult {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_muxcore_notification_v1_notification_proto protoreflect.FileDescriptor

const file_muxcore_notification_v1_notification_proto_rawDesc = "" +
	"\n" +
	"*muxcore/notification/v1/notification.proto\x12\x17muxcore.notification.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe8\x02\n" +
	"\rNotifyRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12=\n" +
	"\bseverity\x18\x03 \x01(\x0e2!.muxcore.notification.v1.SeverityR\bseverity\x12#\n" +
	"\rsource_module\x18\x04 \x01(\tR\fsourceModule\x12<\n" +
	"\bchannels\x18\x05 \x03(\x0e2 .muxcore.notification.v1.ChannelR\bchannels\x12J\n" +
	"\x06fields\x18\x06 \x03(\v22.muxcore.notification.v1.NotifyRequest.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"R\n" +
	"\x0eNotifyResponse\x12@\n" +
	"\aresults\x18\x01 \x03(\v2&.muxcore.notification.v1.ChannelResultR\aresults\"{\n" +
	"\rChannelResult\x12:\n" +
	"\achannel\x18\x01 \x01(\x0e2 .muxcore.notification.v1.ChannelR\achannel\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xfa\x01\n" +
	"\x10ConfigureRequest\x12:\n" +
	"\achannel\x18\x01 \x01(\x0e2 .muxcore.notification.v1.ChannelR\achannel\x12S\n" +
	"\bsettings\x18\x02 \x03(\v27.muxcore.notification.v1.ConfigureRequest.SettingsEntryR\bsettings\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x1a;\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"3\n" +
	"\x11ConfigureResponse\x12\x1e\n" +
	"\n" +
	"configured\x18\x01 \x01(\bR\n" +
	"configured\"\x0f\n" +
	"\rStatusRequest\"T\n" +
	"\x0eStatusResponse\x12B\n" +
	"\bchannels\x18\x01 \x03(\v2&.muxcore.notification.v1.ChannelStatusR\bchannels\"\xea\x01\n" +
	"\rChannelStatus\x12:\n" +
	"\achannel\x18\x01 \x01(\x0e2 .muxcore.notification.v1.ChannelR\achannel\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"last_error\x18\x04 \x01(\tR\tlastError\x12B\n" +
	"\x0flast_success_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\rlastSuccessAt\"I\n" +
	"\vTestRequest\x12:\n" +
	"\achannel\x18\x01 \x01(\x0e2 .muxcore.notification.v1.ChannelR\achannel\"N\n" +
	"\fTestResponse\x12>\n" +
	"\x06result\x18\x01 \x01(\v2&.muxcore.notification.v1.ChannelResultR\x06result*\x87\x01\n" +
	"\aChannel\x12\x17\n" +
	"\x13CHANNEL_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fCHANNEL_DISCORD\x10\x01\x12\x11\n" +
	"\rCHANNEL_SLACK\x10\x02\x12\x13\n" +
	"\x0fCHANNEL_WEBHOOK\x10\x03\x12\x11\n" +
	"\rCHANNEL_EMAIL\x10\x04\x12\x13\n" +
	"\x0fCHANNEL_APPRISE\x10\x05*w\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSEVERITY_INFO\x10\x01\x12\x14\n" +
	"\x10SEVERITY_SUCCESS\x10\x02\x12\x14\n" +
	"\x10SEVERITY_WARNING\x10\x03\x12\x12\n" +
	"\x0eSEVERITY_ERROR\x10\x042\x84\x03\n" +
	"\x13NotificationService\x12Y\n" +
	"\x06Notify\x12&.muxcore.notification.v1.NotifyRequest\x1a'.muxcore.notification.v1.NotifyResponse\x12b\n" +
	"\tConfigure\x12).muxcore.notification.v1.ConfigureRequest\x1a*.muxcore.notification.v1.ConfigureResponse\x12Y\n" +
	"\x06Status\x12&.muxcore.notification.v1.StatusRequest\x1a'.muxcore.notification.v1.StatusResponse\x12S\n" +
	"\x04Test\x12$.muxcore.notification.v1.TestRequest\x1a%.muxcore.notification.v1.TestResponseBXZVgithub.com/Muxcore-Media/contracts-notification/muxcore/notification/v1;notificationv1b\x06proto3"

var (
	file_muxcore_notification_v1_notification_proto_rawDescOnce sync.Once
	file_muxcore_notification_v1_notification_proto_rawDescData []byte
)

func file_muxcore_notification_v1_notification_proto_rawDescGZIP() []byte {
	file_muxcore_notification_v1_notification_proto_rawDescOnce.Do(func() {
		file_muxcore_notification_v1_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_muxcore_notification_v1_notification_proto_rawDesc), len(file_muxcore_notification_v1_notification_proto_rawDesc)))
	})
	return file_muxcore_notification_v1_notification_proto_rawDescData
}

var file_muxcore_notification_v1_notification_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_muxcore_notification_v1_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_muxcore_notification_v1_notification_proto_goTypes = []any{
	(Channel)(0),                  // 0: muxcore.notification.v1.Channel
	(Severity)(0),                 // 1: muxcore.notification.v1.Severity
	(*NotifyRequest)(nil),         // 2: muxcore.notification.v1.NotifyRequest
	(*NotifyResponse)(nil),        // 3: muxcore.notification.v1.NotifyResponse
	(*ChannelResult)(nil),         // 4: muxcore.notification.v1.ChannelResult
	(*ConfigureRequest)(nil),      // 5: muxcore.notification.v1.ConfigureRequest
	(*ConfigureResponse)(nil),     // 6: muxcore.notification.v1.ConfigureResponse
	(*StatusRequest)(nil),         // 7: muxcore.notification.v1.StatusRequest
	(*StatusResponse)(nil),        // 8: muxcore.notification.v1.StatusResponse
	(*ChannelStatus)(nil),         // 9: muxcore.notification.v1.ChannelStatus
	(*TestRequest)(nil),           // 10: muxcore.notification.v1.TestRequest
	(*TestResponse)(nil),          // 11: muxcore.notification.v1.TestResponse
	nil,                           // 12: muxcore.notification.v1.NotifyRequest.FieldsEntry
	nil,                           // 13: muxcore.notification.v1.ConfigureRequest.SettingsEntry
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
}
var file_muxcore_notification_v1_notification_proto_depIdxs = []int32{
	1,  // 0: muxcore.notification.v1.NotifyRequest.severity:type_name -> muxcore.notification.v1.Severity
	0,  // 1: muxcore.notification.v1.NotifyRequest.channels:type_name -> muxcore.notification.v1.Channel
	12, // 2: muxcore.notification.v1.NotifyRequest.fields:type_name -> muxcore.notification.v1.NotifyRequest.FieldsEntry
	4,  // 3: muxcore.notification.v1.NotifyResponse.results:type_name -> muxcore.notification.v1.ChannelResult
	0,  // 4: muxcore.notification.v1.ChannelResult.channel:type_name -> muxcore.notification.v1.Channel
	0,  // 5: muxcore.notification.v1.ConfigureRequest.channel:type_name -> muxcore.notification.v1.Channel
	13, // 6: muxcore.notification.v1.ConfigureRequest.settings:type_name -> muxcore.notification.v1.ConfigureRequest.SettingsEntry
	9,  // 7: muxcore.notification.v1.StatusResponse.channels:type_name -> muxcore.notification.v1.ChannelStatus
	0,  // 8: muxcore.notification.v1.ChannelStatus.channel:type_name -> muxcore.notification.v1.Channel
	14, // 9: muxcore.notification.v1.ChannelStatus.last_success_at:type_name -> google.protobuf.Timestamp
	0,  // 10: muxcore.notification.v1.TestRequest.channel:type_name -> muxcore.notification.v1.Channel
	4,  // 11: muxcore.notification.v1.TestResponse.result:type_name -> muxcore.notification.v1.ChannelResult
	2,  // 12: muxcore.notification.v1.NotificationService.Notify:input_type -> muxcore.notification.v1.NotifyRequest
	5,  // 13: muxcore.notification.v1.NotificationService.Configure:input_type -> muxcore.notification.v1.ConfigureRequest
	7,  // 14: muxcore.notification.v1.NotificationService.Status:input_type -> muxcore.notification.v1.StatusRequest
	10, // 15: muxcore.notification.v1.NotificationService.Test:input_type -> muxcore.notification.v1.TestRequest
	3,  // 16: muxcore.notification.v1.NotificationService.Notify:output_type -> muxcore.notification.v1.NotifyResponse
	6,  // 17: muxcore.notification.v1.NotificationService.Configure:output_type -> muxcore.notification.v1.ConfigureResponse
	8,  // 18: muxcore.notification.v1.NotificationService.Status:output_type -> muxcore.notification.v1.StatusResponse
	11, // 19: muxcore.notification.v1.NotificationService.Test:output_type -> muxcore.notification.v1.TestResponse
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_muxcore_notification_v1_notification_proto_init() }
func file_muxcore_notification_v1_notification_proto_init() {
	if File_muxcore_notification_v1_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_muxcore_notification_v1_notification_proto_rawDesc), len(file_muxcore_notification_v1_notification_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_muxcore_notification_v1_notification_proto_goTypes,
		DependencyIndexes: file_muxcore_notification_v1_notification_proto_depIdxs,
		EnumInfos:         file_muxcore_notification_v1_notification_proto_enumTypes,
		MessageInfos:      file_muxcore_notification_v1_notification_proto_msgTypes,
	}.Build()
	File_muxcore_notification_v1_notification_proto = out.File
	file_muxcore_notification_v1_notification_proto_goTypes = nil
	file_muxcore_notification_v1_notification_proto_depIdxs = nil
}
